### PR TITLE
Update ember-cli and cleanup

### PR DESCRIPTION
**Pull request by charlesdemers**
Major version bump! This code is not backwards compatible!

- Update ember-cli and other dependencies
- Update code to use more ES6 goodness
- Update APIs to be compatible with Ember 1.12
- Remove useless `translate-attr` to follow the removal of `bind-attr` since it can be replaced with subexpressions
- Update tests
- Minor file cleanup

### CODE REVIEW

**Comment by garno** [comment]
It would be nice to have migration steps from `0.3` to `1.0`, *if any*, since it is not backward compatible.

Otherwise, :+1: 

`1.0` :tada:

**Comment by simonprev** [comment]
:+1: When the test suite is :green_apple:

**Comment by charlesdemers** [comment]
@garno I updated the README, is it okay with you?

**Comment by loboulet** [comment]
:+1:

**Pull request merged**
